// AoE4 地图名 英文→中文 映射表
// 来源：游戏内中文本地化 + seicing.com
const MAP_NAMES = {
  // ── 标准地图 ──
  "Altai": "阿尔泰",
  "Ancient Spires": "古代尖山",
  "Archipelago": "群岛",
  "Atacama": "阿塔卡马",
  "Baltic": "波罗的海",
  "Black Forest": "黑森林",
  "Boulder Bay": "巨石湾",
  "Canal": "运河",
  "Canyon": "大峡谷",
  "Carmel": "卡梅尔",
  "Cliffside": "悬崖边",
  "Cliffsanity": "悬崖疯狂",
  "Confluence": "汇流处",
  "Continental": "大陆",
  "Craters": "陨石坑",
  "Danube River": "多瑙河",
  "Dry Arabia": "干燥阿拉伯",
  "Dungeon": "地牢",
  "Enlightened Horizon": "启蒙眼界",
  "Flankwoods": "弗兰克伍兹森林",
  "Forest Ponds": "森林与池塘",
  "Forts": "堡垒",
  "Four Lakes": "四个湖",
  "French Pass": "法兰西隘口",
  "Glade": "林间空地",
  "Golden Heights": "黄金高地",
  "Golden Pit": "黄金之坑",
  "Golden Pits": "黄金之坑",
  "Gorge": "峡谷",
  "Haywire": "失控",
  "Hedgemaze": "树篱迷宫",
  "Hidden Valley": "隐秘山谷",
  "Hideout": "藏身处",
  "High View": "高视野区",
  "Highview": "高视野区",
  "Highwoods": "茂密树林",
  "Hill and Dale": "高山深谷",
  "Himeyama": "姬山",
  "King of the Hill": "占山为王",
  "Lakeside": "湖畔",
  "Land MegaRandom": "陆地超级随机",
  "Lipany": "利帕尼",
  "Marshland": "沼泽地",
  "MegaRandom": "超级随机",
  "Michi": "开道",
  "Migration": "迁移",
  "Mongolian Heights": "蒙古高原",
  "Mountain Clearing": "山中空地",
  "Mountain Lakes": "山间湖泊",
  "Mountain Pass": "隘口",
  "Nagari": "那格利",
  "Nomadic Ridges": "游牧山脊",
  "Nomadic Tarns": "游牧湖群",
  "Oasis": "绿洲",
  "Ocean Gateway": "海之门户",
  "Prairie": "草原",
  "Relic River": "遗迹河",
  "Rocky River": "岩石河",
  "Rugged": "崎岖之地",
  "Shadow Lake": "影子湖",
  "Socotra": "索科特拉岛",
  "Sunkenlands": "沉没之地",
  "The Pit": "深坑",
  "Thickets": "灌木丛",
  "Turtle Ridge": "海龟山脊",
  "Volcanic Island": "火山岛",
  "Warring Islands": "敌对岛屿",
  "Wasteland": "荒地",
  "Waterholes": "水洼",
  "Waterlanes": "水道",
  "Wetlands": "湿地",
  "African Waters": "非洲海域",

  // ── 新增地图 ──
  "Fangs": "尖牙",
  "Ascension": "飞升",
  "Snake River": "蛇河",
  "West Lake": "西湖",
  "Acropolis": "卫城",
  "Channel": "海峡",
  "Haunted Gulch": "阴森幽谷",
  "Narrows": "狭窄区域",
  "Peagee": "佩艾吉",
  "Plains": "平原",
  "Rhinelands": "莱茵兰",
  "River Kingdom": "河流王国",
  "Rolling Rivers": "奔流",
  "Wadden Sea": "瓦登海",

  // ── 锦标赛/自定义地图 ──
  "Anatolian Hills": "安纳托利亚丘陵",
  "Alopecia": "秃地",
  "Atoll": "环礁",
  "Baldland": "荒秃之地",
  "Bazaar": "集市",
  "Bohemia": "波西米亚",
  "Bridges": "桥梁",
  "Coastal": "海岸",
  "Coastal Cliffs": "海岸悬崖",
  "Danube Divide": "多瑙分界",
  "Dry River": "岩石河",
  "Excavation": "挖掘场",
  "Floodplain": "泛滥平原",
  "Lake Side": "湖畔",
  "Moving Out": "迁出",
  "Oases": "绿洲群",
  "Receding": "退潮",
  "Regions": "区域",
  "Sacred Grove": "圣林",
  "Skärgård": "群岛海岸",
  "Transhumance": "转场放牧",
  "Tundra": "冻土",
  "Water Drake": "水龙",
  "Wildernis": "荒野",
};

module.exports = MAP_NAMES;
